### ISSUE TITLE
Global settings not working on Google Nexus

### ISSUE THREAD

**Issue by vishalkohad121** [googlesamples/android-DeviceOwner#1]
Hi,

I have installed this sample app and disable auto time and timezone from app but still I am able to configure time and timezone from default settings of device.

According to my understanding if i disable these setting from sample app then user will not able to configured these settings from default settings of device.

Please check and let me know if i am doing something wrong.
## 

Thanks

**Comment by vishalkohad121** [comment]
Reminder.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
