### ISSUE TITLE
How to install the sample app

### ISSUE THREAD

**Issue by lduparc** [googlesamples/android-DeviceOwner#2]
I'm using the NfcProvisionning sample app but I'm not able to install the deviceOwner app on the child device. This app is already installed on the master device, the child device is well encrypted and the wifi connected but I receive an error during the admin app download.

I test with a Motorola X Style (XT1572) and a Motorola X Force (XT1580) on Android 6.0

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
