### ISSUE TITLE
Does this work at all, seriously?

### ISSUE THREAD

**Issue by nickfurnesschubb** [googlesamples/android-DeviceOwner#3]
I have tried this a few times without success thinking Android 5 was just to qwerky however i have tried with an Android 6 phone and i still cannot get this to work.

I have attached my version of all files. Included with screenshots of my provision app and the error i see when it attempts to go to a web location to get the apk. I have tested this address in a browser to make sure the download works.
I use a checksum utility to generate the checksum value for me.

Can anybody help and point out what is missing. Can anyone hold their hand up and honestly say they have got this working?

[GitHubFiles.zip](https://github.com/googlesamples/android-DeviceOwner/files/425422/GitHubFiles.zip)

[android-DeviceOwner-master.zip](https://github.com/googlesamples/android-DeviceOwner/files/425437/android-DeviceOwner-master.zip)

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
