### ISSUE TITLE
provision without nfc

### ISSUE THREAD

**Issue by vikas0** [googlesamples/android-DeviceOwner#4]
the device i want to install device owner does not have nfc. i have tested with adb shell set device owner for test purpose, but how do i do it to set up unprovisioned device?

**Comment by adatoo** [comment]
Not sure if this answers your query. The command to enable device owner is:
```
adb shell dpm set-device-owner com.example.android.deviceowner/.DeviceOwnerReceiver
```
You need to ideally do this on a device that has just been factory reset.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
